version: "3.9"
services:
  devbox:
    container_name: devbox
    image: healthsamurai/devbox:edge
    depends_on:
      - "db"
    ports:
      - 8888:8888
    env_file:
      # Enter you license data
      - .license
    environment:
      # Aidbox settings
      AIDBOX_PORT           : 8888
      AIDBOX_FHIR_VERSION   : 4.0.0
      AIDBOX_CLIENT_ID      : root
      AIDBOX_CLIENT_SECRET  : secret
      AIDBOX_ADMIN_ID       : admin
      AIDBOX_ADMIN_PASSWORD : secret
      # Aidbox database connection settings
      PGHOST     : db
      PGPORT     : 5432
      PGUSER     : postgres
      PGPASSWORD : postgres
      PGDATABASE : devbox

  db:
    container_name: timescaledb
    image: aidbox/ts-pg12
    ports:
      - 5488:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./pgdata:/var/lib/postgresql/data"

  grafana:
    container_name: grafana
    image: grafana/grafana
    environment:
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_AUTH_ANONYMOUS_ENABLED:   "true"
      GF_SERVER_ENABLE_GZIP: "true"
    volumes:
      - "./grafanadata:/var/lib/grafana"
    ports:
      - 3000:3000
